services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    # Password for your postgres user
    ports:
      - '5434:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "True"
    ports:
      - '5000:80'
    depends_on:
      - db

volumes:
  db:
    driver: local